// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIXQt3cmhKlpA_7pEstxXkbSWCHKfQoz4',
    appId: '1:854078490533:web:3551df8c20f67b6da34a4c',
    messagingSenderId: '854078490533',
    projectId: 'cmdb-auth',
    authDomain: 'cmdb-auth.firebaseapp.com',
    storageBucket: 'cmdb-auth.appspot.com',
    measurementId: 'G-DLND6CD9T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzuc1YtzZ7x2y9QUTiNX8PC3p0T0x9GkY',
    appId: '1:854078490533:android:55b0906124127a73a34a4c',
    messagingSenderId: '854078490533',
    projectId: 'cmdb-auth',
    storageBucket: 'cmdb-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLPI4fj_lm4om_BmoLNcwlCRbmkwp0c8g',
    appId: '1:854078490533:ios:008b99da6491b9d0a34a4c',
    messagingSenderId: '854078490533',
    projectId: 'cmdb-auth',
    storageBucket: 'cmdb-auth.appspot.com',
    iosClientId: '854078490533-ur7i1hm5g53942o0ucb7rjghipilt7pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLPI4fj_lm4om_BmoLNcwlCRbmkwp0c8g',
    appId: '1:854078490533:ios:008b99da6491b9d0a34a4c',
    messagingSenderId: '854078490533',
    projectId: 'cmdb-auth',
    storageBucket: 'cmdb-auth.appspot.com',
    iosClientId: '854078490533-ur7i1hm5g53942o0ucb7rjghipilt7pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieDb',
  );
}
